export declare const CMD_INITIALISE = "init";
export declare const CMD_START = "start";
export declare const CMD_STOP = "stop";
export declare const CMD_UPDATE = "update";
export declare const CMD_ADJUST_DRIFT = "adjust-drift";
export declare const EVENT_READY = "ready";
export declare const EVENT_STARTING = "starting";
export declare const EVENT_STOPPING = "stopping";
export declare const EVENT_TICK = "tick";
//# sourceMappingURL=timer-event-types.d.ts.map